### ISSUE TITLE
NODE_ENV undefined with typescript and nodemon

### ISSUE THREAD

**Issue by minotaurrr** [kentcdodds/cross-env#198] opened 2019-03-11 22:47 UTC
- `cross-env` version: 5.2.0
- `node` version: 10.12.0
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config

```javascript
"dev:ts": "cross-env NODE_ENV=production tsc-watch --onSuccess \"node ./node_modules/nodemon/bin/nodemon.js dist/main.js\""

"dev:ts": "tsc-watch --onSuccess \"cross-env NODE_ENV=production node ./node_modules/nodemon/bin/nodemon.js dist/main.js\""
```

Tried both commands above but `console.log(process.env.NODE_ENV)` prints `undefined`.

Any help is appreciated.

**Comment by geastwood** [comment] 2019-09-20 15:33
Can't reproduce. The environment looks fine.

<img width="2032" alt="Screenshot 2019-09-20 at 17 31 51" src="https://user-images.githubusercontent.com/1623359/65339513-93bd9f80-dbcc-11e9-8b80-fa6bea3b862d.png">

**Comment by kentcdodds** [comment] 2019-10-01 17:30
Sorry for not responding to this earlier. It's been long enough that I'm going to close this issue. If you're still experiencing problems, please open a new issue.

**Closed by kentcdodds** 2019-10-01 17:30 UTC

**Comment by cristian-eriomenco** [comment] 2020-10-28 13:04
@minotaurrr 17 thumbs up i'm encountering same issue, did you found a fix?
